### ISSUE TITLE
Crash on Client related to EntityCreatureTameable

### ISSUE THREAD

**Issue by Kovak** [Lycanite/LycanitesMobs#173]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (zz-backpacks 1.9.4 - 3.1.1.jar)
  LoadingPlugin (VersionChecker-1.3.0.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 8/7/16 3:11 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte
	at lycanite.lycanitesmobs.api.entity.EntityCreatureTameable.isTamed(EntityCreatureTameable.java:449)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureRideable.func_70612_e(EntityCreatureRideable.java:170)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2180)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70636_d(EntityCreatureBase.java:1302)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureAgeable.func_70636_d(EntityCreatureAgeable.java:106)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureTameable.func_70636_d(EntityCreatureTameable.java:177)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureRideable.func_70636_d(EntityCreatureRideable.java:59)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1249)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.World.func_72870_g(World.java:1920)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1788)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lycanite.lycanitesmobs.api.entity.EntityCreatureTameable.isTamed(EntityCreatureTameable.java:449)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureRideable.func_70612_e(EntityCreatureRideable.java:170)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2180)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70636_d(EntityCreatureBase.java:1302)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureAgeable.func_70636_d(EntityCreatureAgeable.java:106)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureTameable.func_70636_d(EntityCreatureTameable.java:177)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureRideable.func_70636_d(EntityCreatureRideable.java:59)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1249)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.World.func_72870_g(World.java:1920)

-- Entity being ticked --
Details:
	Entity Type: swampmobs.eyewig (lycanite.lycanitesmobs.swampmobs.entity.EntityEyewig)
	Entity ID: 1932122
	Entity Name: ~~ERROR~~ ClassCastException: java.lang.String cannot be cast to java.lang.Byte
	Entity's Exact location: 1218.50, 71.00, 410.50
	Entity's Block location: World: (1218,71,410), Chunk: (at 2,4,10 in 76,25; contains blocks 1216,0,400 to 1231,255,415), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1743)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kovak'/1932067, l='MpServer', x=1328.00, y=72.00, z=484.78]]
	Chunk stats: MultiplayerChunkCache: 212, 212
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-2,73,545), Chunk: (at 14,4,1 in -1,34; contains blocks -16,0,544 to -1,255,559), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 36361052 game time, 16963181 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ ClassCastException: java.lang.String cannot be cast to java.lang.Byte
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:390)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1471165176 bytes (1403 MB) / 2528038912 bytes (2410 MB) up to 4241293312 bytes (4044 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.28 Powered by Forge 12.17.0.1976 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1976.jar) 
	UCHIJA	Forge{12.17.0.1976} [Minecraft Forge] (forge-1.9.4-12.17.0.1976.jar) 
	UCHIJA	backpacks16840{3.1.1} [Backpacks!] (zz-backpacks 1.9.4 - 3.1.1.jar) 
	UCHIJA	basemetals{2.3.3} [Base Metals] (BaseMetals_1.9.4-2.3.3.10.jar) 
	UCHIJA	lootablebodies{2.1.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies_1.9.4-2.1.0.jar) 
	UCHIJA	JEI{3.6.8.225} [Just Enough Items] (jei_1.9.4-3.6.8.225.jar) 
	UCHIJA	lycanitesmobs{1.14.3.3 - MC 1.9.4} [Lycanites Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	arcticmobs{1.14.3.3 - MC 1.9.4} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	demonmobs{1.14.3.3 - MC 1.9.4} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	desertmobs{1.14.3.3 - MC 1.9.4} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	forestmobs{1.14.3.3 - MC 1.9.4} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	freshwatermobs{1.14.3.3 - MC 1.9.4} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	infernomobs{1.14.3.3 - MC 1.9.4} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	junglemobs{1.14.3.3 - MC 1.9.4} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	mountainmobs{1.14.3.3 - MC 1.9.4} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	plainsmobs{1.14.3.3 - MC 1.9.4} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	saltwatermobs{1.14.3.3 - MC 1.9.4} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	shadowmobs{1.14.3.3 - MC 1.9.4} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	swampmobs{1.14.3.3 - MC 1.9.4} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar) 
	UCHIJA	poweradvantage{2.2.2} [Power Advantage] (PowerAdvantage_1.9.4-2.2.2.jar) 
	UCHIJA	VersionChecker{1.3.0} [Version Checker] (VersionChecker-1.3.0.jar) 
	UCHIJA	MineKampf{0.55} [MineKampf] (MineKampf-0.55.jar) 
	UCHIJA	orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar) 
	UCHIJA	steamadvantage{2.1.0} [Steam Advantage] (SteamAdvantage_1.9.4-2.1.0.jar) 
	UCHIJA	territorychevsky{b16} [Territorial Dealings] (TerritorialDealings_1.9_b16.jar) 
	UCHIJA	XaeroMinimap{1.9.8} [Xaero's Minimap] (Xaeros_Minimap_1.9.8_Forge_1.9.4.jar) 
	UCHIJA	XaeroWorldMap{1.1.1} [Xaero's World Map] (XaerosWorldMap_b1.1.1_Forge_1.9.4.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (zz-backpacks 1.9.4 - 3.1.1.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (VersionChecker-1.3.0.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13440 Compatibility Profile Context 16.200.1010.1002' Renderer: 'AMD Radeon R9 200 Series'
	Launched Version: 1.9.4-forge1.9.4-12.17.0.1976
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13440 Compatibility Profile Context 16.200.1010.1002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft  32x MC19.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@54996d3e

**Comment by Kovak** [comment]
appears to be the same as #171

**Comment by Lycanite** [comment]
Thanks for the crash report, I may have this fixed in the latest 1.10.2/1.10 release though that has yet to be tested. I found that server wrappers such as mark2 as well as other such as interfaces used by many online Minecraft server services trigger this crash and I've had this occur with vanilla mobs. I'll look into bringing the latest bug fix to 1.9.4 but I can't guarantee that it will fix it.

**Comment by zXTechnoWolf** [comment]
Can confirm that it still happens ver 1.15.1.2

http://pastebin.com/u6etZXiw

**Comment by Lycanite** [comment]
Ok I'm suppressing this crash in the next update (1.15.1.3), let me know if it still happens when it's released.

**Comment by xlxAciDxlx** [comment]
The error still happens. Not sure if it's relevant, but I have yet to get the crash in a normal single player world, but opening the world to LAN makes it happen to other players.
